// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/cachestrategy"
)

// CacheStrategyCreate is the builder for creating a CacheStrategy entity.
type CacheStrategyCreate struct {
	config
	mutation *CacheStrategyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *CacheStrategyCreate) SetName(v string) *CacheStrategyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *CacheStrategyCreate) SetDescription(v string) *CacheStrategyCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *CacheStrategyCreate) SetNillableDescription(v *string) *CacheStrategyCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *CacheStrategyCreate) SetEnabled(v bool) *CacheStrategyCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *CacheStrategyCreate) SetNillableEnabled(v *bool) *CacheStrategyCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetRevision sets the "revision" field.
func (_c *CacheStrategyCreate) SetRevision(v int64) *CacheStrategyCreate {
	_c.mutation.SetRevision(v)
	return _c
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_c *CacheStrategyCreate) SetNillableRevision(v *int64) *CacheStrategyCreate {
	if v != nil {
		_c.SetRevision(*v)
	}
	return _c
}

// SetConfig sets the "config" field.
func (_c *CacheStrategyCreate) SetConfig(v map[string]interface{}) *CacheStrategyCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CacheStrategyCreate) SetCreatedAt(v time.Time) *CacheStrategyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CacheStrategyCreate) SetNillableCreatedAt(v *time.Time) *CacheStrategyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CacheStrategyCreate) SetUpdatedAt(v time.Time) *CacheStrategyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CacheStrategyCreate) SetNillableUpdatedAt(v *time.Time) *CacheStrategyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the CacheStrategyMutation object of the builder.
func (_c *CacheStrategyCreate) Mutation() *CacheStrategyMutation {
	return _c.mutation
}

// Save creates the CacheStrategy in the database.
func (_c *CacheStrategyCreate) Save(ctx context.Context) (*CacheStrategy, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CacheStrategyCreate) SaveX(ctx context.Context) *CacheStrategy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CacheStrategyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CacheStrategyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CacheStrategyCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := cachestrategy.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := cachestrategy.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Revision(); !ok {
		v := cachestrategy.DefaultRevision
		_c.mutation.SetRevision(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := cachestrategy.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := cachestrategy.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CacheStrategyCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CacheStrategy.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := cachestrategy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CacheStrategy.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "CacheStrategy.description"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "CacheStrategy.enabled"`)}
	}
	if _, ok := _c.mutation.Revision(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`ent: missing required field "CacheStrategy.revision"`)}
	}
	if _, ok := _c.mutation.Config(); !ok {
		return &ValidationError{Name: "config", err: errors.New(`ent: missing required field "CacheStrategy.config"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CacheStrategy.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CacheStrategy.updated_at"`)}
	}
	return nil
}

func (_c *CacheStrategyCreate) sqlSave(ctx context.Context) (*CacheStrategy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CacheStrategyCreate) createSpec() (*CacheStrategy, *sqlgraph.CreateSpec) {
	var (
		_node = &CacheStrategy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cachestrategy.Table, sqlgraph.NewFieldSpec(cachestrategy.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(cachestrategy.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(cachestrategy.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(cachestrategy.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Revision(); ok {
		_spec.SetField(cachestrategy.FieldRevision, field.TypeInt64, value)
		_node.Revision = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(cachestrategy.FieldConfig, field.TypeJSON, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(cachestrategy.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(cachestrategy.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CacheStrategy.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CacheStrategyUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *CacheStrategyCreate) OnConflict(opts ...sql.ConflictOption) *CacheStrategyUpsertOne {
	_c.conflict = opts
	return &CacheStrategyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CacheStrategy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CacheStrategyCreate) OnConflictColumns(columns ...string) *CacheStrategyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CacheStrategyUpsertOne{
		create: _c,
	}
}

type (
	// CacheStrategyUpsertOne is the builder for "upsert"-ing
	//  one CacheStrategy node.
	CacheStrategyUpsertOne struct {
		create *CacheStrategyCreate
	}

	// CacheStrategyUpsert is the "OnConflict" setter.
	CacheStrategyUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *CacheStrategyUpsert) SetName(v string) *CacheStrategyUpsert {
	u.Set(cachestrategy.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CacheStrategyUpsert) UpdateName() *CacheStrategyUpsert {
	u.SetExcluded(cachestrategy.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *CacheStrategyUpsert) SetDescription(v string) *CacheStrategyUpsert {
	u.Set(cachestrategy.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CacheStrategyUpsert) UpdateDescription() *CacheStrategyUpsert {
	u.SetExcluded(cachestrategy.FieldDescription)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *CacheStrategyUpsert) SetEnabled(v bool) *CacheStrategyUpsert {
	u.Set(cachestrategy.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CacheStrategyUpsert) UpdateEnabled() *CacheStrategyUpsert {
	u.SetExcluded(cachestrategy.FieldEnabled)
	return u
}

// SetRevision sets the "revision" field.
func (u *CacheStrategyUpsert) SetRevision(v int64) *CacheStrategyUpsert {
	u.Set(cachestrategy.FieldRevision, v)
	return u
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *CacheStrategyUpsert) UpdateRevision() *CacheStrategyUpsert {
	u.SetExcluded(cachestrategy.FieldRevision)
	return u
}

// AddRevision adds v to the "revision" field.
func (u *CacheStrategyUpsert) AddRevision(v int64) *CacheStrategyUpsert {
	u.Add(cachestrategy.FieldRevision, v)
	return u
}

// SetConfig sets the "config" field.
func (u *CacheStrategyUpsert) SetConfig(v map[string]interface{}) *CacheStrategyUpsert {
	u.Set(cachestrategy.FieldConfig, v)
	return u
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *CacheStrategyUpsert) UpdateConfig() *CacheStrategyUpsert {
	u.SetExcluded(cachestrategy.FieldConfig)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CacheStrategyUpsert) SetCreatedAt(v time.Time) *CacheStrategyUpsert {
	u.Set(cachestrategy.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CacheStrategyUpsert) UpdateCreatedAt() *CacheStrategyUpsert {
	u.SetExcluded(cachestrategy.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CacheStrategyUpsert) SetUpdatedAt(v time.Time) *CacheStrategyUpsert {
	u.Set(cachestrategy.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CacheStrategyUpsert) UpdateUpdatedAt() *CacheStrategyUpsert {
	u.SetExcluded(cachestrategy.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CacheStrategy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CacheStrategyUpsertOne) UpdateNewValues() *CacheStrategyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CacheStrategy.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CacheStrategyUpsertOne) Ignore() *CacheStrategyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CacheStrategyUpsertOne) DoNothing() *CacheStrategyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CacheStrategyCreate.OnConflict
// documentation for more info.
func (u *CacheStrategyUpsertOne) Update(set func(*CacheStrategyUpsert)) *CacheStrategyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CacheStrategyUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *CacheStrategyUpsertOne) SetName(v string) *CacheStrategyUpsertOne {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CacheStrategyUpsertOne) UpdateName() *CacheStrategyUpsertOne {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *CacheStrategyUpsertOne) SetDescription(v string) *CacheStrategyUpsertOne {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CacheStrategyUpsertOne) UpdateDescription() *CacheStrategyUpsertOne {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.UpdateDescription()
	})
}

// SetEnabled sets the "enabled" field.
func (u *CacheStrategyUpsertOne) SetEnabled(v bool) *CacheStrategyUpsertOne {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CacheStrategyUpsertOne) UpdateEnabled() *CacheStrategyUpsertOne {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.UpdateEnabled()
	})
}

// SetRevision sets the "revision" field.
func (u *CacheStrategyUpsertOne) SetRevision(v int64) *CacheStrategyUpsertOne {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.SetRevision(v)
	})
}

// AddRevision adds v to the "revision" field.
func (u *CacheStrategyUpsertOne) AddRevision(v int64) *CacheStrategyUpsertOne {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.AddRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *CacheStrategyUpsertOne) UpdateRevision() *CacheStrategyUpsertOne {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.UpdateRevision()
	})
}

// SetConfig sets the "config" field.
func (u *CacheStrategyUpsertOne) SetConfig(v map[string]interface{}) *CacheStrategyUpsertOne {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *CacheStrategyUpsertOne) UpdateConfig() *CacheStrategyUpsertOne {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.UpdateConfig()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CacheStrategyUpsertOne) SetCreatedAt(v time.Time) *CacheStrategyUpsertOne {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CacheStrategyUpsertOne) UpdateCreatedAt() *CacheStrategyUpsertOne {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CacheStrategyUpsertOne) SetUpdatedAt(v time.Time) *CacheStrategyUpsertOne {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CacheStrategyUpsertOne) UpdateUpdatedAt() *CacheStrategyUpsertOne {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CacheStrategyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CacheStrategyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CacheStrategyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CacheStrategyUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CacheStrategyUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CacheStrategyCreateBulk is the builder for creating many CacheStrategy entities in bulk.
type CacheStrategyCreateBulk struct {
	config
	err      error
	builders []*CacheStrategyCreate
	conflict []sql.ConflictOption
}

// Save creates the CacheStrategy entities in the database.
func (_c *CacheStrategyCreateBulk) Save(ctx context.Context) ([]*CacheStrategy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CacheStrategy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CacheStrategyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CacheStrategyCreateBulk) SaveX(ctx context.Context) []*CacheStrategy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CacheStrategyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CacheStrategyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CacheStrategy.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CacheStrategyUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *CacheStrategyCreateBulk) OnConflict(opts ...sql.ConflictOption) *CacheStrategyUpsertBulk {
	_c.conflict = opts
	return &CacheStrategyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CacheStrategy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CacheStrategyCreateBulk) OnConflictColumns(columns ...string) *CacheStrategyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CacheStrategyUpsertBulk{
		create: _c,
	}
}

// CacheStrategyUpsertBulk is the builder for "upsert"-ing
// a bulk of CacheStrategy nodes.
type CacheStrategyUpsertBulk struct {
	create *CacheStrategyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CacheStrategy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CacheStrategyUpsertBulk) UpdateNewValues() *CacheStrategyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CacheStrategy.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CacheStrategyUpsertBulk) Ignore() *CacheStrategyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CacheStrategyUpsertBulk) DoNothing() *CacheStrategyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CacheStrategyCreateBulk.OnConflict
// documentation for more info.
func (u *CacheStrategyUpsertBulk) Update(set func(*CacheStrategyUpsert)) *CacheStrategyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CacheStrategyUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *CacheStrategyUpsertBulk) SetName(v string) *CacheStrategyUpsertBulk {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CacheStrategyUpsertBulk) UpdateName() *CacheStrategyUpsertBulk {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *CacheStrategyUpsertBulk) SetDescription(v string) *CacheStrategyUpsertBulk {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CacheStrategyUpsertBulk) UpdateDescription() *CacheStrategyUpsertBulk {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.UpdateDescription()
	})
}

// SetEnabled sets the "enabled" field.
func (u *CacheStrategyUpsertBulk) SetEnabled(v bool) *CacheStrategyUpsertBulk {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CacheStrategyUpsertBulk) UpdateEnabled() *CacheStrategyUpsertBulk {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.UpdateEnabled()
	})
}

// SetRevision sets the "revision" field.
func (u *CacheStrategyUpsertBulk) SetRevision(v int64) *CacheStrategyUpsertBulk {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.SetRevision(v)
	})
}

// AddRevision adds v to the "revision" field.
func (u *CacheStrategyUpsertBulk) AddRevision(v int64) *CacheStrategyUpsertBulk {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.AddRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *CacheStrategyUpsertBulk) UpdateRevision() *CacheStrategyUpsertBulk {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.UpdateRevision()
	})
}

// SetConfig sets the "config" field.
func (u *CacheStrategyUpsertBulk) SetConfig(v map[string]interface{}) *CacheStrategyUpsertBulk {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *CacheStrategyUpsertBulk) UpdateConfig() *CacheStrategyUpsertBulk {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.UpdateConfig()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CacheStrategyUpsertBulk) SetCreatedAt(v time.Time) *CacheStrategyUpsertBulk {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CacheStrategyUpsertBulk) UpdateCreatedAt() *CacheStrategyUpsertBulk {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CacheStrategyUpsertBulk) SetUpdatedAt(v time.Time) *CacheStrategyUpsertBulk {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CacheStrategyUpsertBulk) UpdateUpdatedAt() *CacheStrategyUpsertBulk {
	return u.Update(func(s *CacheStrategyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CacheStrategyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CacheStrategyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CacheStrategyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CacheStrategyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
