// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/cachestrategy"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CacheStrategyDelete is the builder for deleting a CacheStrategy entity.
type CacheStrategyDelete struct {
	config
	hooks    []Hook
	mutation *CacheStrategyMutation
}

// Where appends a list predicates to the CacheStrategyDelete builder.
func (_d *CacheStrategyDelete) Where(ps ...predicate.CacheStrategy) *CacheStrategyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CacheStrategyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CacheStrategyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CacheStrategyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(cachestrategy.Table, sqlgraph.NewFieldSpec(cachestrategy.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CacheStrategyDeleteOne is the builder for deleting a single CacheStrategy entity.
type CacheStrategyDeleteOne struct {
	_d *CacheStrategyDelete
}

// Where appends a list predicates to the CacheStrategyDelete builder.
func (_d *CacheStrategyDeleteOne) Where(ps ...predicate.CacheStrategy) *CacheStrategyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CacheStrategyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{cachestrategy.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CacheStrategyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
