// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/cachestrategy"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CacheStrategyUpdate is the builder for updating CacheStrategy entities.
type CacheStrategyUpdate struct {
	config
	hooks    []Hook
	mutation *CacheStrategyMutation
}

// Where appends a list predicates to the CacheStrategyUpdate builder.
func (_u *CacheStrategyUpdate) Where(ps ...predicate.CacheStrategy) *CacheStrategyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *CacheStrategyUpdate) SetName(v string) *CacheStrategyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CacheStrategyUpdate) SetNillableName(v *string) *CacheStrategyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CacheStrategyUpdate) SetDescription(v string) *CacheStrategyUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CacheStrategyUpdate) SetNillableDescription(v *string) *CacheStrategyUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *CacheStrategyUpdate) SetEnabled(v bool) *CacheStrategyUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *CacheStrategyUpdate) SetNillableEnabled(v *bool) *CacheStrategyUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetRevision sets the "revision" field.
func (_u *CacheStrategyUpdate) SetRevision(v int64) *CacheStrategyUpdate {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *CacheStrategyUpdate) SetNillableRevision(v *int64) *CacheStrategyUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *CacheStrategyUpdate) AddRevision(v int64) *CacheStrategyUpdate {
	_u.mutation.AddRevision(v)
	return _u
}

// SetConfig sets the "config" field.
func (_u *CacheStrategyUpdate) SetConfig(v map[string]interface{}) *CacheStrategyUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CacheStrategyUpdate) SetCreatedAt(v time.Time) *CacheStrategyUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CacheStrategyUpdate) SetNillableCreatedAt(v *time.Time) *CacheStrategyUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CacheStrategyUpdate) SetUpdatedAt(v time.Time) *CacheStrategyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CacheStrategyMutation object of the builder.
func (_u *CacheStrategyUpdate) Mutation() *CacheStrategyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CacheStrategyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CacheStrategyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CacheStrategyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CacheStrategyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CacheStrategyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cachestrategy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CacheStrategyUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := cachestrategy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CacheStrategy.name": %w`, err)}
		}
	}
	return nil
}

func (_u *CacheStrategyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cachestrategy.Table, cachestrategy.Columns, sqlgraph.NewFieldSpec(cachestrategy.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(cachestrategy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(cachestrategy.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(cachestrategy.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(cachestrategy.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(cachestrategy.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(cachestrategy.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(cachestrategy.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cachestrategy.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cachestrategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CacheStrategyUpdateOne is the builder for updating a single CacheStrategy entity.
type CacheStrategyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CacheStrategyMutation
}

// SetName sets the "name" field.
func (_u *CacheStrategyUpdateOne) SetName(v string) *CacheStrategyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CacheStrategyUpdateOne) SetNillableName(v *string) *CacheStrategyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CacheStrategyUpdateOne) SetDescription(v string) *CacheStrategyUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CacheStrategyUpdateOne) SetNillableDescription(v *string) *CacheStrategyUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *CacheStrategyUpdateOne) SetEnabled(v bool) *CacheStrategyUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *CacheStrategyUpdateOne) SetNillableEnabled(v *bool) *CacheStrategyUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetRevision sets the "revision" field.
func (_u *CacheStrategyUpdateOne) SetRevision(v int64) *CacheStrategyUpdateOne {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *CacheStrategyUpdateOne) SetNillableRevision(v *int64) *CacheStrategyUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *CacheStrategyUpdateOne) AddRevision(v int64) *CacheStrategyUpdateOne {
	_u.mutation.AddRevision(v)
	return _u
}

// SetConfig sets the "config" field.
func (_u *CacheStrategyUpdateOne) SetConfig(v map[string]interface{}) *CacheStrategyUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CacheStrategyUpdateOne) SetCreatedAt(v time.Time) *CacheStrategyUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CacheStrategyUpdateOne) SetNillableCreatedAt(v *time.Time) *CacheStrategyUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CacheStrategyUpdateOne) SetUpdatedAt(v time.Time) *CacheStrategyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CacheStrategyMutation object of the builder.
func (_u *CacheStrategyUpdateOne) Mutation() *CacheStrategyMutation {
	return _u.mutation
}

// Where appends a list predicates to the CacheStrategyUpdate builder.
func (_u *CacheStrategyUpdateOne) Where(ps ...predicate.CacheStrategy) *CacheStrategyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CacheStrategyUpdateOne) Select(field string, fields ...string) *CacheStrategyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CacheStrategy entity.
func (_u *CacheStrategyUpdateOne) Save(ctx context.Context) (*CacheStrategy, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CacheStrategyUpdateOne) SaveX(ctx context.Context) *CacheStrategy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CacheStrategyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CacheStrategyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CacheStrategyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cachestrategy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CacheStrategyUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := cachestrategy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CacheStrategy.name": %w`, err)}
		}
	}
	return nil
}

func (_u *CacheStrategyUpdateOne) sqlSave(ctx context.Context) (_node *CacheStrategy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cachestrategy.Table, cachestrategy.Columns, sqlgraph.NewFieldSpec(cachestrategy.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CacheStrategy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cachestrategy.FieldID)
		for _, f := range fields {
			if !cachestrategy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cachestrategy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(cachestrategy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(cachestrategy.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(cachestrategy.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(cachestrategy.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(cachestrategy.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(cachestrategy.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(cachestrategy.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cachestrategy.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &CacheStrategy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cachestrategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
